README.md, bin/smcat, doc/index-klunky.html, doc/index.html, doc/smcat-online-interpreter.js, src/cli/actions.js, src/cli/normalizations.js, src/cli/validations.js, src/index.js, src/render/ast2dot.js, src/render/dot.states.template.hbs, src/render/dot.states.template.js, src/render/dot.template.hbs, src/render/dot.template.js, src/render/utl.js, test/cli/normalizations.spec.js, test/cli/validations.spec.js, test/parse/fixtures/composite-left-right.dot, test/parse/fixtures/composite-left-right.json, test/parse/fixtures/composite.dot, test/parse/fixtures/composite_no_root_transitions.dot, test/parse/fixtures/kitchensink.dot, test/parse/fixtures/minimal.dot, test/parse/fixtures/pseudostates.dot, test/render/ast2dot.spec.js
in addition to top to bottom, which lives on as the default.
- introduces a `--direction` option to the cli and a `direction` option to the API which can take `top-down` (the default and current way of rendering) and `left-right` as values.
- only makes sense on the `dot` output format, so only used there
- also adds a 'direction' option to the sample html (both the fancy looking one and the clunky looking one)
=> Adds the possibility to render left to right

docs/api.md, docs/hacking.md, types/state-machine-cat.d.ts
See title - helps with ease of use and maintenance
=> doc(types|api): describe how to add a renderer, more strongly type definitions in /types, brush-up of the api doc

src/parse/scxml/normalizeMachine.js, test/parse/scxml.spec.js, test/render/fixtures/510hierarchical-one-initial-state.scxml.re-json, test/render/fixtures/514hierarchical-with-initial-state-pointing-somehwhere-with-an-action.scxml.re-json
Before this PR the scxml parser didn't recognise the initial state in this scxml - now it does
```xml
<?xml version="1.0" encoding="UTF-8"?>
<scxml xmlns="http://www.w3.org/2005/07/scxml" version="1.0">
<initial>
<transition target="closed" />
</initial>
<state id="closed" />
</scxml>
```
=> bugfix(parse-scxml): improve initial recognition

src/cli/normalize.js, test/cli/normalize.spec.js
=> feature(cli): automatically classify .scxml and .xml input extensions as scxml

package.json, src/parse/scxml/index.js, src/parse/scxml/normalizeMachine.js, src/parse/scxml/utl.js
See title. Reduces maintenance effort.
=> refactor(scxml): use lodash.castArray instead of hand rolled utility

.github/workflows/main.yml
> Plan to do something drastic?     
> Leave an [issue](https://github.com/sverweij/dependency-cruiser/issues/new) with a
> summary of the changes you propose + some context on why you'd want to
> do that.
Add main.yml file for github action.
Instead of lastest, there is 12.x version for Nodejs.
It follows https://github.com/sverweij/dependency-cruiser/pull/197.
The `npm run check` command means `run-p --aggregate-output depcruise lint test:cover`, which cover the commands executed in the gitlab-ci.yml file.
Related to this issue https://github.com/sverweij/state-machine-cat/issues/83
No tests
=> feat(ci): set-up github action

lgtm.yml
see title
Out of the box lgtm takes into account way too much. This PR attempts to configure it so it only looks at that what matters.
- By submitting a PR.
=> ci(lgtm): configure lgtm so it doesn't look at generated code

README.md, bin/smcat, docs/faq.md, package.json, src/cli/makeDescription.js, test/cli/makeDescription.spec.js
=> doc(cli): document viz.js warning on node 12

.github/workflows/lint-test-linux.yml, .github/workflows/lint-test-macos.yml, .github/workflows/lint-test-windows.yml, .travis.yml
- see title - because it makes builds faster
- split off macOS & windows builds in separate workflows so they're easier to restart individually.
- on travis don't run node 8 anymore
By making this PR and doing several pushes to it
=> ci(gh-actions): set up node modules cache

README.md, docs/XMI.md, docs/dev/index.html, docs/index.hbs, docs/index.html
As explained in XMI.md
> XMI is a gnarly format which takes a lot of effort to do well, with little or no return.
> On top of that it has many tastes between suppliers, so xmi created with one
> tool will not work or look like something a truck rode over in another.
>
> If you want to interchange state machines with a well defined standard - please have a
> look at state-machine-cat's [SCXML](./SCXML.md) support.
- eyeballs (no code was harmed in the making if this PR)
=> bugfix(doc): deprecate xmi as an output format

.github/workflows/lint-test-linux.yml, .github/workflows/lint-test-macos.yml, .github/workflows/lint-test-windows.yml, src/parse/smcat/peg/smcat-parser.pegjs, src/parse/smcat/smcat-parser.js, test/parse/01-transitions-only.json
Escaped quotes (`"\""`) were output in the parse tree as `"\\\""`, which caused #121. This PR fixes that.
fixes #121 
=> bugfix(parse): properly output parsed escaped quotes

src/parse/smcat-ast.schema.json, types/state-machine-cat.d.ts
- adds the `width` attribute on the type of transitions
- adds sensible restrictions on the width in the json schema
- type refs need to be in sync with reality
=> bugfix(types|json-schema): type the width attribute on transitions

bin/smcat.mjs, docs/faq.md, src/cli/make-description.mjs, test/cli/make-description.spec.mjs
- updates the vizjs warning `--help` shows to be more actionable
- updates the condition under which the warning shows:
- _before_: always show under node >= 12
- _after_: always show when the GraphViz' `dot` command isn't available
- updates the FAQ to match the message in --help
The `Invalid asm.js` message does indeed occur under node >=12, but only when GraphViz dot isn't installed. Also node >= 12 is not a distinguishing factor anymore as the only nodejs versions state-machine-cat supports are >= 12 anyway.
- I am ok with the stuff in …
=> feature(cli): updates the vizjs warning & the condition under which it shows

README.md, bin/smcat.mjs, package.json, src/cli/actions.mjs, src/cli/file-name-to-stream.mjs, src/options.mjs, src/render/index-node.mjs, src/render/vector/dot-to-vector-native.mjs, src/render/vector/vector-native-dot-with-fallback.mjs, test/render/vector/dot-to-vector-native.spec.mjs, test/render/vector/vector-native-dot-with-fallback.spec.mjs
- adds png and pdf output to the command line version
- only works with the _native_ graphviz dot (not with viz.js,  which we use as a fallback and that doesn't support these formats).
needs
fixes #165 
=> feature: adds png and pdf output formats (native graphviz only)

.github/workflows/ci.yml, package.json, src/parse/parser-helpers.mjs, src/parse/scxml/index.mjs, src/parse/scxml/normalize-machine.mjs, src/parse/scxml/scxml.d.ts, tools/istanbul-json-summary-to-markdown.mjs
- set up diff graph output in GHA step summary
- also removes the CodeQL action as part of PR's (it never uncovered anything and it is not fast about it - having it in a nightly is more than enough until further notice).
There was something like that in already - but made it consistent with the setup in my other repos.
=> chore(ci): set up diff graph output in GHA step summary

.github/workflows/ci.yml
- sets code-climate submit action version range more broadly so there's less LCM to do
- has dependency-cruiser emit performance logs (supporting its beta testing)
=> chore(ci): sets code-climate submit action version range more broadly

package.json, test/bin.spec.mts, test/cli/actions.spec.mts, test/index.spec.mts, test/parse/scxml.spec.mts, test/parse/smcat-parser.spec.mts, test/render/json.spec.mts, test/render/scjson/index.spec.mts
- replaces chai-xml with the xml parser we're using in the regular code as well
- replaces chai-json-schema with ajv
Less dependencies = less worries
=> refactor(test): replaces chai-xml, chai-json-schema with (chai-less) alternatives

dist/parse/scxml/index.mjs, dist/parse/scxml/normalize-machine.mjs, dist/parse/scxml/utl.mjs, dist/render/index-node.mjs, dist/render/index.mjs, dist/transform/desugar.mjs, dist/utl.mjs, package.json, src/parse/scxml/index.mjs, src/parse/scxml/normalize-machine.mts, src/parse/scxml/utl.mts, src/render/dot/index.mjs, src/render/dot/state-transformers.mts, src/render/index-node.mts, src/render/index.mts, src/render/smcat/index.mts, src/transform/desugar.mts, src/utl.mts
- replaces instances of castArray, reject and has with (just as straightforward) native variants
- replaces cloneDeep with the json hack. When nodejs 16 stops being supported we can switch it to structuredClone.
less dependencies === less pain
=> refactor: replaces lodash functions where a good native alternative exists

dist/parse/smcat/smcat-parser.mjs, src/parse/smcat/peg/smcat-parser.peggy, src/parse/smcat/smcat-parser.mjs
- removes (unused) AST emission code for comments, spaces and line-ends from the smcat parser
Makes the parser code a little bit smaller, probably a tiny bit faster - and a little easier to understand.
=> refactor(parse/smcat): removes (unused) ast emission code for comments, spaces and line-ends

.github/workflows/ci.yml, package-lock.json, package.json
- see title
Follow nodejs release cycle
=> ci!: drops support for node 16 and 19 - BREAKING

package.json, test/cli/actions.spec.mts, test/cli/attributes-parser.spec.mts, test/cli/execute-command-line.spec.mts, test/cli/file-name-to-stream.spec.mts, test/cli/normalize.spec.mts, test/cli/validations.spec.mts, test/index.spec.mts, test/parse/scxml.spec.mts, test/parse/smcat-parser.spec.mts, test/render/dot/attributebuilder.spec.mts, test/render/dot/counter.spec.mts, test/render/dot/index.spec.mts, test/render/dot/state-transformers.spec.mts, test/render/dot/transition-transformers.spec.mts, test/render/dot/utl.spec.mts, test/render/json.spec.mts, test/render/scjson/index.spec.mts, test/render/scjson/make-valid-event-names.spec.mts, test/render/scjson/make-valid-xml-name.spec.mts, test/render/scxml.spec.mts, test/render/smcat.spec.mts, test/render/vector/dot-to-vector-native.spec.mts, test/render/vector/vector-native-dot-with-fallback.spec.mts, test/render/vector/vector-with-wasm.spec.mts, test/state-machine-model.spec.mts, test/transform/desugar-forks.spec.mts, test/transform/desugar-joins.spec.mts, test/transform/desugar-junctions.spec.mts, test/transform/desugar.spec.mts
- uses subpath imports in tests
Improves readability and maintainability.
=> refactor(test): starts using subpath imports in tests
